### ISSUE TITLE
Fatal error: Uncaught Error: Class 'WPSEO_News_Sitemap' not found

### ISSUE THREAD

**Issue by thehawk79** [Yoast/wpseo-news#447]
Hi,
i installed the News Seo plugin but I receive a fatal error message when I try to active it.

Fatal error: Uncaught Error: Class 'WPSEO_News_Sitemap' not found in /***/wp-content/plugins/wpseo-news-trunk/wpseo-news.php:67 Stack trace: #0 /***/wp-content/plugins/wpseo-news-trunk/wpseo-news.php(75): yoast_wpseo_news_clear_sitemap_cache() #1 /***/wp-includes/class-wp-hook.php(286): yoast_wpseo_news_activate('') #2 /***/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #3 /***/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #4 /***/wp-admin/plugins.php(180): do_action('activate_wpseo-...') #5 {main} thrown in /***/plugins/wpseo-news-trunk/wpseo-news.php on line 67

**Comment by andizer** [comment]
Thanks for reporting this issue. 
Unfortunately, we do not have enough information to reproduce this problem. Please follow [these guidelines](http://kb.yoast.com/article/180-how-to-write-a-good-bug-report) to improve your [bug report](http://kb.yoast.com/article/180-how-to-write-a-good-bug-report).

Also, it may help us a lot if you can provide a backtrace of the error encountered. [This gist](https://gist.github.com/jrfnl/5925642) will explain how to enable the backtrace in your website: https://gist.github.com/jrfnl/5925642

Thank you.

**Comment by moorscode** [comment]
Closing this due to inactivity.

**Comment by ethanclevenger91** [comment]
Gonna float an idea here. If you clone from this repo to use on your site, the above error will pop when you activate. Gotta run `composer install` to get the autoload file.

Cloning from here seemed easier than telling my client to go back, download a zip, and send it to me. Just had to figure out that missing piece.
